### ISSUE TITLE
Configuration prefixes are inconsistent

### ISSUE THREAD

**Issue by robhruska** [hudl/Mjolnir#42]
Timeouts start with `command.`, but other configs start with `mjolnir.` This can be confusing. Should they be consistent?

**Comment by agilejon** [comment]
For me, I care more about discoverability. When things are going wrong I would like to be able to discover how to tweak a configuration value. If we do that via consistent naming - that works for me.

**Comment by robhruska** [comment]
Addressed in #47 (Version 2.6.0)
