### ISSUE TITLE
Unable to get circuit breaker to open.

### ISSUE THREAD

**Issue by sds88** [hudl/Mjolnir#52]
I'm testing out using Mjolnir with a rest api that my company is developing, and I'm unable to get a sample command I created to trip it's circuit breaker.  

I added a `throw new Exception()` to the body of my ExecuteAsync function so it fails every time, after executing it many times I never get any exceptions corresponding to the circuit breaker being blown.  

For reference this is what I have in my config file related to circuit breakers
```
mjolnir.breaker.default.minimumOperations=2
mjolnir.breaker.default.thresholdPercentage=50
mjolnir.breaker.default.trippedDurationMillis=60000
mjolnir.metrics.default.windowMillis=30000
mjolnir.metrics.default.snapshotTtlMillis=1000
```

**Comment by sds88** [comment]
From what I can tell after cloning the repo and stepping through, no config values I set are being used at all. This could be why I can't get the circuit breaker to open.

**Comment by lewislabs** [comment]
Are you setting the config provider correctly? e.g.
`ConfigProvider.UseProvider(new FileConfigurationProvider(@"c:\path\to", "config-file.txt"));`

**Comment by sds88** [comment]
I was using the overload as such:
`ConfigProvider.UseProvider(new FileConfigurationProvider(@"c:\path\to\config-file.txt"));` 
Shouldn't have done that apparently :smile:   Splitting it up correctly loaded the configs I set.

**Comment by lewislabs** [comment]
great, glad that works for you!
