### ISSUE TITLE
BulkheadConfigGauge not firing

### ISSUE THREAD

**Issue by sds88** [hudl/Mjolnir#53]
Hello (I'm not sure if you want this as an issue since it's referring to the updated pre-release version), I've recently updated to 2.6 and the `BulkheadConfigGauge` events do not seem to ever be firing.  I have a single bulkhead set up (`recommendations-isolation`) with the following config:
```
mjolnir.bulkhead.recommendations-isolation.maxConcurrent=100
mjolnir.bulkheadConfigGaugeIntervalMillis=60000
```

**Comment by robhruska** [comment]
Yeah, filing an issue here perfect for 2.6 issues. I'll have a look this week sometime. Out of curiosity, what's in your implementation of `IMetricEvents`? Are you just piping them through to a log or something?

**Comment by sds88** [comment]
We are piping them to New Relic Insights, so every IMetricEvent function pretty much looks like this:
```
public void EventName(params...)
{
  var eventAttributes = new Dictionary<string, object>
  {
    ...All function params get put in here
  }
  NewRelic.RecordCustomEvent(nameof(EventName), eventAttributes);
}
```

**Comment by robhruska** [comment]
Cool, thanks for the insight! I've got this on my list of stuff to tackle this week. Thanks again.

**Comment by robhruska** [comment]
I've been digging into this a bit. Do any of the other gauge events work for you, or is it just the `BulkheadConfigGauge` that's broken?

**Comment by sds88** [comment]
The `BreakerConfigGauge` event does fire for us with the correct parameters

**Comment by sschneider1207** [comment]
@robhruska any updates on this/2.6 in general?

**Comment by robhruska** [comment]
This should be fixed, thanks again for the report. Working on shipping 2.6 tonight. Thanks for the bump. :+1:
